### ISSUE TITLE
Missing 'bl_idname' attribute for some classes

### ISSUE THREAD

**Issue by Harvester62** [Stability-AI/stability-blender-addon-public#1]
A properly formatted 'bl_idname' is missing for the following classes (I've added the correct code) in the file ui.py to avoid warnings in the Blender console:

class StabilityImageEditorPanel(PanelSectionImageEditor, Panel):

    bl_idname = "IMAGE_EDITOR_PT_stability_image_editor"
    
class RenderOptionsPanelSection3DEditor(PanelSection3D, Panel):

    bl_idname = "VIEW_3D_PT_render_options"

class RenderOptionsPanelSectionImageEditor(PanelSectionImageEditor, Panel):

    bl_idname = "IMAGE_EDITOR_PT_render_options"

class AdvancedOptionsPanelSection3DEditor(PanelSection3D, Panel):

    bl_idname = "VIEW_3D_PT_advanced_options"

class AdvancedOptionsPanelSectionImageEditor(PanelSectionImageEditor, Panel):

    bl_idname = "IMAGE_PT_advanced_options"

I am not a Python programmer and the above code has been given by Chat-GPT analyzing the code and the warning messages in the Blender console. Thank you for your add-on.

**Comment by brianfitzgerald** [comment]
Thanks so much for pointing this out! I've added idnames to the panels you've listed, and those will be included in the next release of the addon.

**Comment by Harvester62** [comment]
I am glad to have been helpful, Brian.
